import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Playmo Waitlist',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://artprojectsforkids.org/wp-content/uploads/2016/08/Easy-Owl-700.jpg" sizes="any" />

      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
